### ISSUE TITLE
Order is not maintain

### ISSUE THREAD

**Issue by stanegit** [chrismichaelscott/iugo#10]
Hi here is another one

here is model
  task_model =
              tasks:[
                    {name:'task1'}
                    {name:'task2'}
              ]

here is template

 <ul class="bindto-tasks">
                        <li data-bind_each>
                            <span data-bind_key="name"></span> <a href="./${name}" class="-mydelete" data-app="${name}">delete ${name}</a>
                        </li>
                    </ul>

it displays fine but if you move mouse on "a" it shows wrong ${name}

**Comment by chrismichaelscott** [comment]
Hi,

Thanks again.

I've made the fix, see this jsfiddle: http://jsfiddle.net/chrismichaelscott/Hw8aX/

Let me know if that works.

**Comment by stanegit** [comment]
Works thx
